#MODEL:
model_name: regnety_040
num_classes: 19
pretrained_backbone: True
separable_convolution: False

#OPTIM:
epochs: 160
resume: False
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
class_weight: null

#TRAIN:
batch_size: 16
train_size: 481
mixed_precision: True

#TEST:
val_size: 513

#benchmark
warmup_iter: 3
num_iter: 30

save_every_k_epochs: 3
save_last_k_epochs: 8
dataset_name: cityscapes
dataset_dir: cityscapes_dataset
aug_mode: baseline
pretrained_path: ''
resume_path: /content/drive/My Drive/Colab Notebooks/SemanticSegmentation/checkpoints/cityscapes_regnety40_latest
save_best_path: /content/drive/My Drive/Colab Notebooks/SemanticSegmentation/checkpoints/cityscapes_regnety40
save_latest_path: /content/drive/My Drive/Colab Notebooks/SemanticSegmentation/checkpoints/cityscapes_regnety40_latest

#save_best_path: checkpoints/voc_regnety40_mixed_precision
#save_latest_path: checkpoints/voc_regnety40_mixed_precision_latest
